config/routes.rb
RandysEcommerceStore::Application.routes.draw do
  resources :cart_items

  root :to => 'products#index'
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  resources :provinces
  resources :products
  resources :orders
  resources :line_items
  resources :customers
  resources :platforms
  resources :contact_us
  resources :about_us

  match "/search_results" => "products#search_results"
  match "/sales" => "products#sales"
  match "/recently_updated" => "products#recently_updated"
  match "/login" => "customers#login"
  match "/login_form" => "customers#login_form"
  match "/register" => "customers#new"
  match "/logout" => "customers#logout"

end

app/models/about_u.rb
class AboutU < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  attr_accessible :customer_id, :product_id, :quantity
end

app/models/contact_u.rb
class ContactU < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :address, :city, :country, :email, :name, :postal_code, :province_id, :password
  validates_presence_of :address, :city, :country, :email, :postal_code, :province_id
  belongs_to :province
  has_many :orders
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  attr_accessible :order_id, :price, :product_id, :quantity
  belongs_to :product
  belongs_to :order
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :customer_id, :gst, :hst, :payment_identifier, :payment_processor, :pst, :status, :subtotal, :total
  belongs_to :customer
end

app/models/platform.rb
class Platform < ActiveRecord::Base
  attr_accessible :description, :image, :name
  has_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :name, :platform_id, :price, :stock_quantity, :image, :on_sale, :sale_price
  belongs_to :platform
  has_many :line_items
end

app/models/province.rb
class Province < ActiveRecord::Base
  attr_accessible :code, :gst, :home_province, :hst, :name, :pst
  has_many :customers
end

app/controllers/about_us_controller.rb
class AboutUsController < InheritedResources::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(params[:order])

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.order("name").page(params[:page]).per(5)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  def search_results
    keywords = params[:keywords]
    @products = Product.where("name LIKE '%#{keywords}%'")
    if @products.empty?
      @safety = "No products found."
    else
      @safety = ""
    end
    respond_to do |format|
    format.html # search_results.html.erb
    format.json { render json: @products }
    end
  end

  def sales
    @products = Product.where(:on_sale => true)
    respond_to do |format|
      format.html # sales.html.erb
      format.json { render json: @products }
    end
  end

  def recently_updated
    @products = Product.order("updated_at").reverse
    respond_to do |format|
      format.html # newest.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/views/about_us/_form.html.erb
<%= form_for(@about_u) do |f| %>
  <% if @about_u.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@about_u.errors.count, "error") %> prohibited this about_u from being saved:</h2>

      <ul>
      <% @about_u.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/about_us/edit.html.erb
<h1>Editing about_u</h1>

<%= render 'form' %>

<%= link_to 'Show', @about_u %> |
<%= link_to 'Back', about_us_path %>

app/views/about_us/index.html.erb
<h2>About us<small>Who we are what we do</small></h2>
<% @about_us.each do |about_u| %>
    <%= about_u.content %>
<% end %>

app/views/about_us/new.html.erb
<h1>New about_u</h1>

<%= render 'form' %>

<%= link_to 'Back', about_us_path %>

app/views/about_us/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @about_u.title %>
</p>

<p>
  <b>Content:</b>
  <%= @about_u.content %>
</p>


<%= link_to 'Edit', edit_about_u_path(@about_u) %> |
<%= link_to 'Back', about_us_path %>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :total %><br />
    <%= f.text_field :total %>
  </div>
  <div class="field">
    <%= f.label :subtotal %><br />
    <%= f.text_field :subtotal %>
  </div>
  <div class="field">
    <%= f.label :pst %><br />
    <%= f.text_field :pst %>
  </div>
  <div class="field">
    <%= f.label :gst %><br />
    <%= f.text_field :gst %>
  </div>
  <div class="field">
    <%= f.label :hst %><br />
    <%= f.text_field :hst %>
  </div>
  <div class="field">
    <%= f.label :payment_processor %><br />
    <%= f.text_field :payment_processor %>
  </div>
  <div class="field">
    <%= f.label :payment_identifier %><br />
    <%= f.text_field :payment_identifier %>
  </div>
  <div class="field">
    <%= f.label :customer_id %><br />
    <%= f.number_field :customer_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <tr>
    <th>Status</th>
    <th>Total</th>
    <th>Subtotal</th>
    <th>Pst</th>
    <th>Gst</th>
    <th>Hst</th>
    <th>Payment processor</th>
    <th>Payment identifier</th>
    <th>Customer</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @orders.each do |order| %>
  <tr>
    <td><%= order.status %></td>
    <td><%= order.total %></td>
    <td><%= order.subtotal %></td>
    <td><%= order.pst %></td>
    <td><%= order.gst %></td>
    <td><%= order.hst %></td>
    <td><%= order.payment_processor %></td>
    <td><%= order.payment_identifier %></td>
    <td><%= order.customer_id %></td>
    <td><%= link_to 'Show', order %></td>
    <td><%= link_to 'Edit', edit_order_path(order) %></td>
    <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Status:</b>
  <%= @order.status %>
</p>

<p>
  <b>Total:</b>
  <%= @order.total %>
</p>

<p>
  <b>Subtotal:</b>
  <%= @order.subtotal %>
</p>

<p>
  <b>Pst:</b>
  <%= @order.pst %>
</p>

<p>
  <b>Gst:</b>
  <%= @order.gst %>
</p>

<p>
  <b>Hst:</b>
  <%= @order.hst %>
</p>

<p>
  <b>Payment processor:</b>
  <%= @order.payment_processor %>
</p>

<p>
  <b>Payment identifier:</b>
  <%= @order.payment_identifier %>
</p>

<p>
  <b>Customer:</b>
  <%= @order.customer_id %>
</p>


<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :platform_id %><br />
    <%= f.number_field :platform_id %>
  </div>
  <div class="field">
    <%= f.label :on_sale %><br />
    <%= f.check_box :on_sale %>
  </div>
  <div class="field">
    <%= f.label :sale_price %><br />
    <%= f.text_field :sale_price %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :stock_quantity %><br />
    <%= f.number_field :stock_quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h2>Latest Games <small>The best games available to date</small></h2>

<%= paginate @products %>

<% @products.each do |product| %>
<article class="products span2">
    <%= image_tag(product.image) %>
    <h5><%= product.name %></h5>
    <% case product.platform_id %>
	  <% when 1 %>
	    <p>On Xbox 360</p>
	  <% when 2 %>
	    <p>On Playstation 3</p>
	  <% when 3 %>
	    <p>On Nintendo Wii</p>
	  <% when 4 %>
	  	<p>On PC</p>
	<% end %>
    <span>$<%= product.price %></span>
    <% if (product.stock_quantity > 0) %>
        <p><b>Stock:</b> <%= product.stock_quantity %></p>
    <% else %>
        <p><b>Out of stock!</b></p>
    <% end if %>
    <%= link_to 'View', product %>
</article>
<% end %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/recently_updated.html.erb
<h2>Recently Updated<small>Whats new..</small></h2>

<% @products.each do |product| %>
<article class="products span2">
    <%= image_tag(product.image) %>
    <h5><%= product.name %></h5>
    <small>$<%= product.price %></small>
    <% if (product.stock_quantity > 0) %>
        <p><b>Stock:</b> <%= product.stock_quantity %></p>
    <% else %>
        <p><b>Out of stock!</b></p>
    <% end if %>
    <%= link_to 'View Details', product %>
</article>
<% end %>

app/views/products/sales.html.erb
<h2>Onsale Items <small>Get em' while they're hot</small></h1>

<% @products.each do |product| %>
<article class="onsale span2">
    <%= image_tag(product.image) %>
    <h5><%= product.name %></h5>
    <small>Reg. $<%= product.price %></small>
    <span>$<%= product.sale_price %></span>
    <% if (product.stock_quantity > 0) %>
        <p><b>Stock:</b> <%= product.stock_quantity %></p>
    <% else %>
        <p><b>Out of stock!</b></p>
    <% end if %>
    <%= link_to 'View Details', product %>
</article>
<% end %>

app/views/products/search_results.html.erb
<h2>Looking for something?<small>Maybe we can find it for you</small></h2>
<% @products.each do |product| %>
  <h3><%= link_to(product.name, "products/#{product.id}") %></h3>
<% end %>
<p><%= @safety %></p>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @product.name %></h2>

<%= image_tag(@product.image, :alt => @product.name, :class => "boxart") %>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>

<p>
  <b>Stock quantity:</b>
  <%= @product.stock_quantity %>
</p>

<p>
  <b>Platform:</b>
    <% case @product.platform_id %>
    <% when 1 %>
      Xbox 360
    <% when 2 %>
      Playstation 3
    <% when 3 %>
      Nintendo Wii
    <% when 4 %>
      PC
  <% end %>
</p>

<%= link_to 'Back', products_path %>