config/routes.rb
RandysEcommerceStore::Application.routes.draw do
  resources :cart_items

  root :to => 'products#index'
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  resources :provinces
  resources :products
  resources :orders
  resources :line_items
  resources :customers
  resources :platforms
  resources :contact_us
  resources :about_us

  match "/search_results" => "products#search_results"
  match "/sales" => "products#sales"
  match "/recently_updated" => "products#recently_updated"
  match "/login" => "customers#login"
  match "/login_form" => "customers#login_form"
  match "/register" => "customers#new"
  match "/logout" => "customers#logout"

end

app/models/about_u.rb
class AboutU < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  attr_accessible :customer_id, :product_id, :quantity
end

app/models/contact_u.rb
class ContactU < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :address, :city, :country, :email, :name, :postal_code, :province_id, :password
  validates_presence_of :address, :city, :country, :email, :postal_code, :province_id
  belongs_to :province
  has_many :orders
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  attr_accessible :order_id, :price, :product_id, :quantity
  belongs_to :product
  belongs_to :order
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :customer_id, :gst, :hst, :payment_identifier, :payment_processor, :pst, :status, :subtotal, :total
  belongs_to :customer
end

app/models/platform.rb
class Platform < ActiveRecord::Base
  attr_accessible :description, :image, :name
  has_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :name, :platform_id, :price, :stock_quantity, :image, :on_sale, :sale_price
  belongs_to :platform
  has_many :line_items
end

app/models/province.rb
class Province < ActiveRecord::Base
  attr_accessible :code, :gst, :home_province, :hst, :name, :pst
  has_many :customers
end

app/controllers/about_us_controller.rb
class AboutUsController < InheritedResources::Base
end

app/controllers/cart_items_controller.rb
class CartItemsController < InheritedResources::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(params[:order])

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/views/cart_items/_form.html.erb
<%= form_for(@cart_item) do |f| %>
  <% if @cart_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart_item.errors.count, "error") %> prohibited this cart_item from being saved:</h2>

      <ul>
      <% @cart_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :customer_id %><br />
    <%= f.number_field :customer_id %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cart_items/edit.html.erb
<h1>Editing cart_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart_item %> |
<%= link_to 'Back', cart_items_path %>

app/views/cart_items/index.html.erb
<h1>Listing cart_items</h1>

<table>
  <tr>
    <th>Customer</th>
    <th>Product</th>
    <th>Quantity</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cart_items.each do |cart_item| %>
  <tr>
    <td><%= cart_item.customer_id %></td>
    <td><%= cart_item.product_id %></td>
    <td><%= cart_item.quantity %></td>
    <td><%= link_to 'Show', cart_item %></td>
    <td><%= link_to 'Edit', edit_cart_item_path(cart_item) %></td>
    <td><%= link_to 'Destroy', cart_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart item', new_cart_item_path %>

app/views/cart_items/new.html.erb
<h1>New cart_item</h1>

<%= render 'form' %>

<%= link_to 'Back', cart_items_path %>

app/views/cart_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Customer:</b>
  <%= @cart_item.customer_id %>
</p>

<p>
  <b>Product:</b>
  <%= @cart_item.product_id %>
</p>

<p>
  <b>Quantity:</b>
  <%= @cart_item.quantity %>
</p>


<%= link_to 'Edit', edit_cart_item_path(@cart_item) %> |
<%= link_to 'Back', cart_items_path %>